created new layput and handler
buitoancnth/nus_fotobook pull request #4
Opened 2018-09-04 04:06 UTC by buitoancnth

2018-09-04 10:30 UTC, xuanchien requested changes

2018-09-04 10:30 UTC, xuanchien commented on app/assets/javascripts/image_onclick.js
> +      // $('.prev').on('click', function(){
Vì sao code này bị comment? Mình có cần dùng nữa? Nếu không dùng thì mình remove luôn

2018-09-04 10:30 UTC, xuanchien commented on app/assets/stylesheets/custom.scss
> +    vertical-align: middle;
Indentation khác với những nơi khác

2018-09-04 10:30 UTC, xuanchien commented on app/views/albums/index.html.erb
> +<center><%= paginate @albums %></center>
thẻ `<center>` là thẻ HTML cũ, lên HTML5 thì nó sẽ không support nữa nên mình cũng sẽ không dùng nó. Nên dùng thẻ `<div>` kết hợp với CSS để cho nó center

2018-09-04 10:30 UTC, xuanchien commented on app/views/kaminari/_page.html.erb
> +    <%= content_tag :a, page, data: { remote: remote }, rel: (page.next? ? 'next' : (page.prev? ? 'prev' : nil)), class: 'page-link' %>
Tại sao phía dưới dùng `link_to` còn ở đây mình dùng thẻ `content_tag`? Có gì khác biệt chăng?

Và nếu chỉ có class của thẻ `<li>` là khác nhau thì thay vì dùng `if` ở ngoài, mình sẽ làm như thế này

`<li class="page-item <%= page.current? ? 'active' : '' %>">`

2018-09-04 10:30 UTC, xuanchien commented on app/views/layouts/application.html.erb
> +        		<%= yield %>
Sai indentation

2018-09-04 10:30 UTC, xuanchien commented on app/views/photos/index.html.erb
> +<center><%= paginate @photos %></center>
Không nên dùng thẻ `<center>`. Lý do như một comment ở trên

2018-09-04 10:30 UTC, xuanchien commented on app/views/photos/my_photos.html.erb
> +    <%= image_tag("image2.jpg", class: 'iamge') %>
Sai chính tả trong class name, đúng là `image`

2018-09-05 02:38 UTC, buitoancnth commented on app/views/kaminari/_page.html.erb
> +    <%= content_tag :a, page, data: { remote: remote }, rel: (page.next? ? 'next' : (page.prev? ? 'prev' : nil)), class: 'page-link' %>
gem này nó hỗ trợ, tạo ra view như thế luôn anh, 2 cái này thì nội dung nó khác nhau nên không viết gộp được.

2018-09-05 07:36 UTC, merged