Upload image with paperclip and usage postgres database
buitoancnth/nus_fotobook pull request #5
Opened 2018-09-06 02:10 UTC by buitoancnth

2018-09-06 04:46 UTC, xuanchien requested changes

2018-09-06 04:46 UTC, xuanchien commented on app/controllers/albums_controller.rb
> +      if params[:images]
Nếu tạo album thành công mà không có hình ảnh nào hết thì sao? Khi đó code của em chưa thấy xử lý trường hợp đó

2018-09-06 04:46 UTC, xuanchien commented on app/controllers/albums_controller.rb
> +    # render :index
Dư code bị comment

2018-09-06 04:46 UTC, xuanchien commented on app/controllers/feeds_controller.rb
> +    # redirect_to photos_path
Dư code bị comment

2018-09-06 04:46 UTC, xuanchien commented on app/controllers/photos_controller.rb
>      # render :index
Dư commented code

2018-09-06 04:46 UTC, xuanchien commented on app/controllers/sessions_controller.rb
> +class SessionsController < Devise::SessionsController
Có cần phải override file SessionsController hay không? Tại sao cần phải override?

2018-09-06 04:46 UTC, xuanchien commented on app/models/photo.rb
> +  validates_attachment :image, content_type: { content_type: /\Aimage\/.*\z/ },attachment_presence: true
cần phân tách chữ `attachment_presence` với dấu phẩy phía trước

2018-09-06 04:46 UTC, xuanchien commented on app/models/photo.rb
> +  # do_not_validate_attachment_file_type :image
Commented code

2018-09-06 04:46 UTC, xuanchien commented on app/views/albums/my_albums.html.erb
> +<%= link_to '<button type="button" class="btn-primary">Add Album</button>'.html_safe, new_album_path%><hr>
Không nên dùng cách `html_safe` như thế này, cách làm đúng là như sau

```
<%= link_to(new_album_path) do %>
   <button type="button" class="btn btn-primary">Add Album</button>
<% end %>
```

Và button có thiếu class `btn` hay không?

2018-09-06 04:46 UTC, xuanchien commented on app/views/albums/my_albums.html.erb
> +<center><%= paginate @albums %></center>
Sao vẫn tiếp tục dùng thẻ `<center>` vậy? Bootstrap nó đã có hỗ trợ center dùng class `text-center` thì phải

2018-09-06 04:46 UTC, xuanchien commented on app/views/albums/new.html.erb
> +<h3 class="text-primary">New Album</h3><hr>
Thẻ `<hr>` cần phải đặt trên 1 dòng riêng

2018-09-06 04:46 UTC, xuanchien commented on app/views/albums/new.html.erb
> +  <%= f.submit nil, class: 'btn-primary'%>
Tại sao giá trị là `nil` ở đây? Class của button có thiếu `btn` hay không?

2018-09-06 04:46 UTC, xuanchien commented on app/views/photos/new.html.erb
> +  <%= f.submit %>
Button cần có class của Bootstrap

2018-09-06 04:46 UTC, xuanchien commented on app/views/photos/my_photos.html.erb
> +<%= button_to "Add Photo", { action: "new" }, method: :get, class: 'btn-primary upload' %>
Thiếu class `btn`

2018-09-06 04:46 UTC, xuanchien commented on app/views/photos/new.html.erb
> +  <%= f.label :title %>
Form như thế này là chưa đúng kiểu của bootstrap, cần xem trên trang Bootstrap form tạo ra có những thẻ gì, class như thế nào và làm tương ứng. Ví dụ `<div class="form-group">`

2018-09-06 04:46 UTC, xuanchien commented on app/views/albums/new.html.erb
> +  <%= f.label :title %>
Form như thế này là chưa đúng kiểu của bootstrap, cần xem trên trang Bootstrap form tạo ra có những thẻ gì, class như thế nào và làm tương ứng. Ví dụ `<div class="form-group">`

2018-09-06 04:46 UTC, xuanchien commented on db/migrate/20180904072855_change_column_photo.rb
> +    change_column :photos, :album_id, :integer
Tại sao up và down đều giống như nhau? Nếu vậy thì migration này dùng để làm gì?

2018-09-06 06:30 UTC, buitoancnth commented on db/migrate/20180904072855_change_column_photo.rb
> +    change_column :photos, :album_id, :integer
cái này bữa  e  test  dùng để set cho khóa ngoại bằng 0 để add data, e xóa cái thuộc tính trong def down rồi. file này không cần thiết a.

2018-09-06 07:00 UTC, buitoancnth commented on app/controllers/sessions_controller.rb
> +class SessionsController < Devise::SessionsController
em override vì sau này khi đăng nhập xong e thêm flash với lại render hay redirect_to , mà em thêm vào chưa xử lý.

2018-09-06 07:28 UTC, xuanchien commented on app/controllers/sessions_controller.rb
> +class SessionsController < Devise::SessionsController
Tại sao em cần thêm Flash với lại render? Có yêu cầu gì đặc biệt hay không?

2018-09-06 07:29 UTC, xuanchien requested changes

2018-09-06 07:29 UTC, xuanchien commented on app/views/albums/my_albums.html.erb
> +  <button type="button" class="btn btn-primary">Add Album</button>
Chưa dùng `i18n`

2018-09-06 07:29 UTC, xuanchien commented on app/views/albums/new.html.erb
> +    <h3>Some errors were found:</h3>
Chưa dùng `i18n`

2018-09-06 07:29 UTC, xuanchien commented on app/views/photos/my_photos.html.erb
> +  <button type="button" class="btn btn-primary">Add Photo</button>
Chưa dùng `i18n`

2018-09-06 07:29 UTC, xuanchien commented on app/views/photos/new.html.erb
> +<h3 class="text-primary">New Photo</h3>
Chưa dùng i18n

2018-09-06 07:29 UTC, xuanchien commented on app/views/photos/new.html.erb
> +    <h3>Some errors were found:</h3>
Chưa dùng i18n

2018-09-07 14:24 UTC, xuanchien requested changes

2018-09-07 14:24 UTC, xuanchien commented on app/assets/stylesheets/custom.scss
> +	color: #fff;
Indentation lộn xộn quá

2018-09-07 14:24 UTC, xuanchien commented on app/assets/stylesheets/custom.scss
> +  align-content: center;
Đây là thuộc tính dùng cho flex, e có đang dùng đúng không vậy? https://www.w3schools.com/cssref/css3_pr_align-content.asp

2018-09-07 14:24 UTC, xuanchien commented on app/assets/stylesheets/custom.scss
> +div.caption p {
Chưa tận dụng được sức mạnh của SCSS. Em có thể khai báo như sau

```
div.caption {
   p {
   }

  span {
  }
}
```

2018-09-07 14:24 UTC, xuanchien commented on app/assets/stylesheets/custom.scss
> +i {
Em override nguyên thẻ <i> luôn sao? Tại sao lại làm như vậy? Thẻ i thì nó là để in nghiêng, không được thay đổi các thuộc tính của nó như vậy

2018-09-07 14:24 UTC, xuanchien commented on app/controllers/albums_controller.rb
> +  before_action :load_image, only: :create
Hàm của em đặt tên không đúng, theo nội dung a đọc thì hàm đó e dùng để check có params[:images] được gửi lên server hay không, cần rename hàm cho đúng

2018-09-10 01:52 UTC, xuanchien requested changes

2018-09-10 01:52 UTC, xuanchien commented on app/assets/stylesheets/custom.scss
> +  span:hover {
Cái này có thể để ngay trong thẻ `span` ở trên, như sau

```
span {
   &:hover{
   }
}
```

2018-09-10 01:52 UTC, xuanchien commented on app/controllers/albums_controller.rb
> +    return if @images
Logic này hơi khó hiểu cho người đọc, nếu là check coi có params image hay không thì nên viết logic như sau

```
unless @images
   redirect_to new_album_path
end
```

2018-09-10 01:52 UTC, xuanchien commented on app/controllers/photos_controller.rb
>    def my_photos
Cần phân tách 2 methods bằng một dòng trống

2018-09-10 01:52 UTC, xuanchien commented on app/models/photo.rb
> +  scope :photo_pucblic, -> { where(share_mode: true) }
Lỗi chính tả `pucblic`. Và scope này đã nằm trong model Photo nên không cần phải có chữ `photo_` ở đầu nữa, chỉ cần đặt `scope :public` là được

2018-09-10 01:52 UTC, xuanchien commented on app/views/albums/_album.html.erb
> +      <div class="pop"><%= image_tag("image2.jpg",size: "200x200", class: '') %></div>
Class rỗng để làm gì? Nếu không có class thì không cần chỉ định gì cả

2018-09-10 01:52 UTC, xuanchien commented on app/views/albums/_album.html.erb
> +        <h5 class="post-name text-primary" ><%= User.find(album.user_id).fullname %></h5>
Dùng truy vấn SQL như thế này trong View là không OK. Và tại sao không dùng association giữa `user` với `album`?

2018-09-10 01:52 UTC, xuanchien commented on app/views/albums/_album.html.erb
> +        <span class="post-date">24/05/2018</span>
Mấy con số này vẫn chưa load từ db lên à?

2018-09-10 01:52 UTC, xuanchien commented on app/views/devise/sessions/new.html.erb
> +        <%= f.email_field :email, autofocus: true, autocomplete: 'email', placeholder: "Email", class: 'form-control' %>
Placeholder như thế này cũng nên dùng i18n

2018-09-10 01:52 UTC, xuanchien commented on app/views/layouts/_footer.html.erb
>  <footer class="footer">
Có còn dùng Footer nữa hay không? Nếu không dùng thì nên xóa file luôn

2018-09-10 01:52 UTC, xuanchien commented on app/views/layouts/_header.html.erb
> +            <li><%= link_to "Edit User Profile", edit_user_registration_path %></li>
Chưa dùng i18n

2018-09-10 01:52 UTC, xuanchien commented on app/views/layouts/_header.html.erb
> +          <%= link_to "Log out", destroy_user_session_path, method: :delete %>
Chưa dùng i18n

2018-09-10 01:52 UTC, xuanchien commented on app/views/layouts/_header.html.erb
> +        <li><%= link_to "Log in", new_user_session_path %></li>
Chưa dùng i18n

2018-09-10 01:52 UTC, xuanchien commented on app/views/photos/_photo.html.erb
> +        <h5 class="post-name text-primary" ><%= User.find(photo.user_id).fullname %></h5>
Không được dùng User.find như thế này trong view, cần dùng association

2018-09-10 01:52 UTC, xuanchien commented on app/views/photos/_photo.html.erb
> +        <span class="post-date"><%= Time.zone.at(photo.created_at).strftime("%I:%M %p %m/%d/%Y") %></span>
Đưa hàm format này vào 1 helper, chỗ khác cũng dùng lại được. Khi cần format thì chỉ cần gọi như sau

```
<%= format_time(photo.created_at) %>
```

2018-09-10 01:52 UTC, xuanchien commented on app/views/photos/_photo.html.erb
> +  <% if index == 1 %>
Logic khúc này nữa là sao? Tại sao nếu index là 1 thì sẽ có các thẻ div như vậy?

2018-09-10 01:52 UTC, xuanchien commented on app/views/photos/my_photos.html.erb
> +    <% if index == 3 %>
Logic này để làm gì?

2018-09-10 10:31 UTC, xuanchien requested changes

2018-09-10 10:31 UTC, xuanchien commented on app/controllers/albums_controller.rb
> +    @albums = Album.album_public.order_by_created_at.page params[:page]
scope trong album thì không cần prefix 'album_' nữa

2018-09-10 10:31 UTC, xuanchien commented on app/controllers/albums_controller.rb
> +    flash[:success] = "deleted success !"
Chưa có i18n cho message

2018-09-10 10:31 UTC, xuanchien commented on app/models/photo.rb
> +  scope :photo_public, -> { where(share_mode: true) }
Không cần để tiền tố là `photo_` trong scope này, chỉ cần để `public` là được

2018-09-10 10:31 UTC, xuanchien commented on app/models/album.rb
> +  scope :album_public, -> { where(share_mode: true) }
Không cần để `album_` trong scope này

2018-09-10 10:31 UTC, xuanchien commented on app/models/photo.rb
> +  def check_album_id?
Nên đặt tên hàm là `no_album?`

2018-09-10 10:31 UTC, xuanchien commented on app/views/albums/my_albums.html.erb
> +            <% break if index == 3 %>
Mục đích đoạn if này là gì?

2018-09-10 10:31 UTC, xuanchien commented on app/views/devise/registrations/new.html.erb
> +        <%= f.text_field :last_name, autofocus: true, placeholder: t('.last_name'), class: 'form-control' %>
Dư autofocus

2018-09-10 10:31 UTC, xuanchien commented on app/views/devise/registrations/new.html.erb
> +        <%= f.email_field :email, autofocus: true, placeholder: t('.email'), class: 'form-control' %>
Dư autofocus

2018-09-11 03:28 UTC, xuanchien requested changes

2018-09-11 03:28 UTC, xuanchien commented on app/views/layouts/_header.html.erb
> +          <%= link_to t('logout'), destroy_user_session_path, method: :delete %>
Nên dùng lazy lookup thay vì đặt key `logout` ở level 1 như trong file locales.

2018-09-11 03:28 UTC, xuanchien commented on app/views/layouts/_header.html.erb
> +        <li><%= link_to t('login'), new_user_session_path %></li>
Nên dùng lazy lookup thay vì đặt key `login` ở level 1 như trong file locales.

2018-09-11 03:28 UTC, xuanchien commented on app/views/layouts/_head_include.html.erb
> +<meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
A có xem lại thì thẻ <meta> sẽ không cần thẻ đóng, em remove thẻ đóng </meta> đi

2018-09-11 03:28 UTC, xuanchien commented on app/views/devise/registrations/edit.html.erb
> +        <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
Chưa dùng i18n

2018-09-11 03:28 UTC, xuanchien commented on app/views/devise/registrations/edit.html.erb
> +          <em>(<%= @minimum_password_length %> characters minimum)  </em>
Chưa dùng i18n

2018-09-11 03:28 UTC, xuanchien commented on app/views/devise/registrations/edit.html.erb
> +        <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
Chưa dùng i18n

2018-09-11 03:28 UTC, xuanchien commented on app/views/devise/registrations/edit.html.erb
> +          <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
Chưa dùng i18n

2018-09-11 03:28 UTC, xuanchien commented on app/models/album.rb
> +    @images.each do |image|
Nên gọi hàm `create_images` bên trong này thay vì viết lại logic tạo images

2018-09-11 15:41 UTC, buitoancnth commented on app/views/albums/my_albums.html.erb
> +            <% break if index == 3 %>
số 3 này là em mún cho cái album chỉ show tối đa 3 ảnh trong cái album có số ảnh phía trong ấy a
để e đặt lại biến constant

2018-09-11 15:42 UTC, buitoancnth commented on app/views/layouts/_header.html.erb
> +          <%= link_to t('logout'), destroy_user_session_path, method: :delete %>
có mấy cái chung em hay dùng em để ở mục ngoài cùng không biết đc không anh

2018-09-11 15:45 UTC, xuanchien commented on app/views/layouts/_header.html.erb
> +          <%= link_to t('logout'), destroy_user_session_path, method: :delete %>
Cũng được nếu như em đã hiểu khi nào cần lazy lookup, khi nào không

2018-09-12 01:30 UTC, merged