create admin
buitoancnth/nus_fotobook pull request #7
Opened 2018-09-12 01:52 UTC by buitoancnth

2018-09-12 02:07 UTC, xuanchien requested changes

2018-09-12 02:07 UTC, xuanchien commented on .gitignore
> +/public/system/photos/images/000/000/063/original/img6.jpeg
Không để từng file như thế này trong gitignore, làm sao e biết sẽ có bao nhiêu file mà để cho hết? Cần để dạng thư mục

2018-09-12 02:07 UTC, xuanchien commented on app/controllers/photos_controller.rb
> +    @photos = Photo.search(params[:search]).order(sort_column + " " + sort_direction).page params[:page]
`sort_column` và `sort_direction` ở đâu ra vậy?

2018-09-12 02:07 UTC, xuanchien commented on app/models/user.rb
> +  def active_for_authentication?
Có hàm này rồi thì có cần dùng before_action `active_user` trong application_controller?

2018-09-12 02:07 UTC, xuanchien commented on app/views/admin/albums/index.html.erb
> +            <% break if index == 3 %>
e dùng `MAX_IMAGE_SHOW` chỗ nào?

Đoạn này nếu limit 3 thì nên viết 1 hàm trong album để trả về tối đa 3 photos để hiển thị, trong view không nên có logic này

2018-09-12 02:07 UTC, xuanchien commented on app/views/admin/users/edit.html.erb
> +      <% if @user.avatar.present? %>
Nên dùng option `default` của paperclip và config trong model thay vì if else trong view như thế này

2018-09-12 02:07 UTC, xuanchien commented on app/views/admin/users/index.html.erb
> +  <%= render 'user',users: @users %>
tên partial đặt là `_user.html` (số ít) trong khi nhiệm vụ của partial lại là để hiện thị danh sách các users (số nhiều) => không hợp lý

2018-09-12 02:15 UTC, buitoancnth commented on app/models/user.rb
> +  def active_for_authentication?
hàm này em viết mà nó lỗi,  hàm e viết trong đây xí e xóa,

2018-09-12 06:57 UTC, xuanchien requested changes

2018-09-12 06:57 UTC, xuanchien commented on app/controllers/albums_controller.rb
> +      @albums = Album.shared.search(params[:search]).includes(:photos).page(params[:page]).per(4)
Bị duplicate code khúc này, nó chỉ khác nhau là 1 cái gọi hàm search, 1 cái không. Có cách nào gom lại thành 1 đoạn code thôi không?

2018-09-12 06:57 UTC, xuanchien commented on app/controllers/photos_controller.rb
> +    unless params[:search].blank?
Tương tự bên phần album, code đang bị duplicate

2018-09-12 06:57 UTC, xuanchien commented on app/models/album.rb
> +  scope :search, -> word { where("title LIKE '%#{word}%'") }
Không được dùng trực tiếp String Interpolation khi thực hiện truy vấn thế này.

2018-09-12 06:57 UTC, xuanchien commented on app/models/album.rb
> +  def image_in_album
tên hàm không phản ánh đúng nội dung hàm. Cần rename lại cho đúng. Ví dụ: `top_photos`

2018-09-12 06:57 UTC, xuanchien commented on app/models/album.rb
> +    self.photos.first(3)
Magic number

2018-09-12 06:57 UTC, xuanchien commented on app/models/photo.rb
> +  scope :image_not_in_album, -> { where("user_id IS NOT NULL") }
Tại sao scope tên là `image_not_in_album` mà lại so sánh cột `user_id` thay vì cột `album_id`?

2018-09-12 06:57 UTC, xuanchien commented on app/models/photo.rb
> +  scope :search, -> word { where("title LIKE '%#{word}%'") }
Không đúng best practices khi dùng cách truy vấn như thế này

2018-09-12 06:57 UTC, xuanchien commented on app/views/layouts/admin_layout.html.erb
> +    <title><%= t('titel_app') %></title>
sai chính tả

2018-09-12 06:57 UTC, xuanchien commented on app/views/layouts/application.html.erb
> +    <title><%= t('titel_app') %></title>
sai chính tả

2018-09-12 06:57 UTC, xuanchien commented on app/views/layouts/layout_album_photo.html.erb
> +    <title><%= t('titel_app') %></title>
sai chính tả

2018-09-12 06:57 UTC, xuanchien commented on config/locales/en.yml
> +  titel_app: "FotoBook"
sai chính tả

2018-09-13 03:17 UTC, xuanchien requested changes

2018-09-13 03:17 UTC, xuanchien commented on app/models/album.rb
> +      all
Không dùng all ở đây

2018-09-13 03:17 UTC, xuanchien commented on app/models/user.rb
> +      all
Không dùng all ở đây

2018-09-13 03:17 UTC, xuanchien commented on app/controllers/albums_controller.rb
> +    @albums = Album.shared.order_by_created_at.includes(:photos).search(params[:search]).page(params[:page]).per(4)
Magic number

2018-09-13 03:17 UTC, xuanchien commented on app/controllers/albums_controller.rb
> +    @albums = Album.shared.order_by_created_at.includes(:photos).page(params[:page]).per(4)
Magic number

2018-09-13 03:17 UTC, xuanchien commented on app/controllers/application_controller.rb
> +  def admin_user
tên hàm nên là `check_admin_user` để phản ánh nội dung của hàm là check một điều kiện gì đó. Nếu để `admin_user` thì nó sẽ có nghĩa là load admin user từ database ra và return user đó

2018-09-13 03:17 UTC, xuanchien commented on app/controllers/photos_controller.rb
> +    @photos = Photo.shared.not_in_album.order_by_created_at.search(params[:search]).page(params[:page]).per(4)
Magic number

2018-09-13 03:20 UTC, buitoancnth commented on app/models/user.rb
> +      all
commit cuối e push lên thay đổi rồi a.

2018-09-13 08:49 UTC, merged